
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ADD ASSIGN COS DIV EQ ERR GT GTE INT INTDIV LBRACKET LIST LPAREN LT LTE MUL NEQ POW RBRACKET REAL RPAREN SIN SUB TAN VARexpression : VAR ASSIGN expressionexpression : expression ADD expression\n                  | expression SUB expression\n                  | expression MUL expression\n                  | expression DIV expression\n                  | expression POW expressionexpression : LPAREN expression RPARENexpression : INT\n                  | REALexpression : VARexpression : LIST LBRACKET INT RBRACKET'
    
_lr_action_items = {'VAR':([0,3,7,8,9,10,11,12,],[2,2,2,2,2,2,2,2,]),'LPAREN':([0,3,7,8,9,10,11,12,],[3,3,3,3,3,3,3,3,]),'INT':([0,3,7,8,9,10,11,12,14,],[4,4,4,4,4,4,4,4,22,]),'REAL':([0,3,7,8,9,10,11,12,],[5,5,5,5,5,5,5,5,]),'LIST':([0,3,7,8,9,10,11,12,],[6,6,6,6,6,6,6,6,]),'$end':([1,2,4,5,15,16,17,18,19,20,21,23,],[0,-10,-8,-9,-2,-3,-4,-5,-6,-1,-7,-11,]),'ADD':([1,2,4,5,13,15,16,17,18,19,20,21,23,],[7,-10,-8,-9,7,7,7,7,7,7,7,-7,-11,]),'SUB':([1,2,4,5,13,15,16,17,18,19,20,21,23,],[8,-10,-8,-9,8,8,8,8,8,8,8,-7,-11,]),'MUL':([1,2,4,5,13,15,16,17,18,19,20,21,23,],[9,-10,-8,-9,9,9,9,9,9,9,9,-7,-11,]),'DIV':([1,2,4,5,13,15,16,17,18,19,20,21,23,],[10,-10,-8,-9,10,10,10,10,10,10,10,-7,-11,]),'POW':([1,2,4,5,13,15,16,17,18,19,20,21,23,],[11,-10,-8,-9,11,11,11,11,11,11,11,-7,-11,]),'ASSIGN':([2,],[12,]),'RPAREN':([2,4,5,13,15,16,17,18,19,20,21,23,],[-10,-8,-9,21,-2,-3,-4,-5,-6,-1,-7,-11,]),'LBRACKET':([6,],[14,]),'RBRACKET':([22,],[23,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,3,7,8,9,10,11,12,],[1,13,15,16,17,18,19,20,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> VAR ASSIGN expression','expression',3,'p_assignment','main.py',126),
  ('expression -> expression ADD expression','expression',3,'p_expression_arithmetic','main.py',130),
  ('expression -> expression SUB expression','expression',3,'p_expression_arithmetic','main.py',131),
  ('expression -> expression MUL expression','expression',3,'p_expression_arithmetic','main.py',132),
  ('expression -> expression DIV expression','expression',3,'p_expression_arithmetic','main.py',133),
  ('expression -> expression POW expression','expression',3,'p_expression_arithmetic','main.py',134),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','main.py',147),
  ('expression -> INT','expression',1,'p_expression_number','main.py',151),
  ('expression -> REAL','expression',1,'p_expression_number','main.py',152),
  ('expression -> VAR','expression',1,'p_expression_var','main.py',156),
  ('expression -> LIST LBRACKET INT RBRACKET','expression',4,'p_expression_list_access','main.py',160),
]
